#!/bin/bash
# NGS-4-ECOPROD - Download example data for Nanope
# Dominik Schneider, 2023-06-23



# Define help

Help()
{
   echo
   echo -e "\033[1;32mSyntax:" 
   echo -e "\033[0;37mngs4_download_np_example -i <ngs4ecoprod_example_data_folder>"
   echo
   echo -e "\033[1;32mExample:"
   echo -e "\033[0;37mngs4_download_np_example -i ~/ngs4ecoprod/ngs4ecoprod/example_data"
   echo
   echo -e "\033[1;32mOptions:"
   echo -e "\033[0;37m"
   echo "         -i     Example data folder"
   echo "         -h     Print this help"
   echo
}



# Define options

while getopts i:":h" flag
do
    case "${flag}" in
        i) install_dir=${OPTARG};;
        h) Help;exit;;
       \?) echo -e "\033[1;31mError: Invalid option";echo -e "\033[0;37m";exit;;
    esac
done



# Error handling
set -e

if [ $# -eq 0 ]; then
    >&2 Help
    exit 1
fi

IF="$install_dir/nanopore"
if [ -d "$IF" ]; then
  echo -e "\033[1;31mError database folder $IF exists. Exiting..."
  echo -e "\033[0;37m"
  exit 1
fi

if [ -d "$IF" ]; then
  mkdir $install_dir
fi

# Main script

echo
echo -e "\033[1;31m-------------------------------------"
echo -e "\033[1;31mNGS-4-ECOPROD silva database download"
echo -e "\033[1;31m-------------------------------------"
echo -e "\e[37m"
echo "Installation folder:             $install_dir/nanopore"



# Download and extract silva database
echo
echo -e "\033[1;33mDownloading example data for ngs4_np_ scripts..."
echo -e "\e[37m"
mkdir $install_dir/nanopore
cd $install_dir/nanopore
prefetch SRR17913199
cd SRR17913199
fasterq-dump SRR17913199.sra
rm SRR17913199.sra -f
pigz -9 SRR17913199.fastq

mv SRR17913199.fastq.gz ../
cd ..
rmdir SRR17913199



# End script
echo
echo -e "\033[1;31mNGS-4-ECOPROD Nanopore example data downloaded"
echo -e "\033[0;37m"